### PR TITLE
Fix incompatible pointer type

### PR DESCRIPTION
**Pull request by hughcars**
Compiling with gcc 15 on `eb358820a32db60100a042ce9bc8b99a88e41d1e` I have errors due to miscasting of `bp->Buff` which is `char*` to `Int*` in `BI_ivmcopy` and `BI_imvcopy` and various other of these copy methods. These were introduced in https://github.com/Reference-ScaLAPACK/scalapack/pull/137 which exposed that the buffer class being used with these methods is a char*, whereas these all assume matching type buffers. 

This fixes the issue with a cast, but is not attempting to understand if these buffers are actually appropriately sized, which is a much bigger question. This will restore the previous behaviour, (by masking it with the cast), but is not endorsing the handling of these buffers in any way.

Example error message:
```

[  3%] Building C object CMakeFiles/scalapack.dir/BLACS/SRC/cgsum2d_.c.o
/path/to/build-gcc/extern/scalapack/BLACS/SRC/igsum2d_.c: In function 'igsum2d_':
/path/to/build-gcc/extern/scalapack/BLACS/SRC/igsum2d_.c:154:49: error: passing argument 5 of 'BI_imvcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  154 |       BI_imvcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
      |                                               ~~^~~~~~
      |                                                 |
      |                                                 char *
In file included from /path/to/build-gcc/extern/scalapack/BLACS/SRC/igsum2d_.c:1:
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:136:53: note: expected 'int *' but argument is of type 'char *'
  136 | void BI_imvcopy(Int m, Int n, Int *A, Int lda, Int *buff);
/path/to/build-gcc/extern/scalapack/BLACS/SRC/igsum2d_.c:169:56: error: passing argument 5 of 'BI_ivmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  169 |             BI_ivmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
      |                                                     ~~~^~~~~~
      |                                                        |
      |                                                        char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:137:53: note: expected 'int *' but argument is of type 'char *'
  137 | void BI_ivmcopy(Int m, Int n, Int *A, Int lda, Int *buff);
/path/to/build-gcc/extern/scalapack/BLACS/SRC/igsum2d_.c:175:53: error: passing argument 5 of 'BI_ivmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  175 |          BI_ivmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
      |                                                  ~~~^~~~~~
      |                                                     |
      |                                                     char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:137:53: note: expected 'int *' but argument is of type 'char *'
  137 | void BI_ivmcopy(Int m, Int n, Int *A, Int lda, Int *buff);
/path/to/build-gcc/extern/scalapack/BLACS/SRC/igsum2d_.c:229:52: error: passing argument 5 of 'BI_ivmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  229 |          BI_ivmcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
      |                                                  ~~^~~~~~
      |                                                    |
      |                                                    char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:137:53: note: expected 'int *' but argument is of type 'char *'
  137 | void BI_ivmcopy(Int m, Int n, Int *A, Int lda, Int *buff);
/path/to/build-gcc/extern/scalapack/BLACS/SRC/sgsum2d_.c: In function 'sgsum2d_':
make[6]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/igsum2d_.c.o] Error 1
make[6]: *** Waiting for unfinished jobs....
/path/to/build-gcc/extern/scalapack/BLACS/SRC/sgsum2d_.c:154:49: error: passing argument 5 of 'BI_smvcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  154 |       BI_smvcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
      |                                               ~~^~~~~~
      |                                                 |
      |                                                 char *
In file included from /path/to/build-gcc/extern/scalapack/BLACS/SRC/sgsum2d_.c:1:
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:138:57: note: expected 'float *' but argument is of type 'char *'
  138 | void BI_smvcopy(Int m, Int n, float *A, Int lda, float *buff);
      |                                                  ~~~~~~~^~~~
/path/to/build-gcc/extern/scalapack/BLACS/SRC/sgsum2d_.c:167:56: error: passing argument 5 of 'BI_svmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  167 |             BI_svmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
      |                                                     ~~~^~~~~~
      |                                                        |
      |                                                        char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:139:57: note: expected 'float *' but argument is of type 'char *'
  139 | void BI_svmcopy(Int m, Int n, float *A, Int lda, float *buff);
      |                                                  ~~~~~~~^~~~
/path/to/build-gcc/extern/scalapack/BLACS/SRC/sgsum2d_.c:173:53: error: passing argument 5 of 'BI_svmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  173 |          BI_svmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
      |                                                  ~~~^~~~~~
      |                                                     |
      |                                                     char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:139:57: note: expected 'float *' but argument is of type 'char *'
  139 | void BI_svmcopy(Int m, Int n, float *A, Int lda, float *buff);
      |                                                  ~~~~~~~^~~~
/path/to/build-gcc/extern/scalapack/BLACS/SRC/sgsum2d_.c:227:52: error: passing argument 5 of 'BI_svmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  227 |          BI_svmcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
      |                                                  ~~^~~~~~
      |                                                    |
      |                                                    char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:139:57: note: expected 'float *' but argument is of type 'char *'
  139 | void BI_svmcopy(Int m, Int n, float *A, Int lda, float *buff);
      |                                                  ~~~~~~~^~~~
make[6]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/sgsum2d_.c.o] Error 1
/path/to/build-gcc/extern/scalapack/BLACS/SRC/dgsum2d_.c: In function 'dgsum2d_':
/path/to/build-gcc/extern/scalapack/BLACS/SRC/dgsum2d_.c:154:49: error: passing argument 5 of 'BI_dmvcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  154 |       BI_dmvcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
      |                                               ~~^~~~~~
      |                                                 |
      |                                                 char *
In file included from /path/to/build-gcc/extern/scalapack/BLACS/SRC/dgsum2d_.c:1:
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:134:59: note: expected 'double *' but argument is of type 'char *'
  134 | void BI_dmvcopy(Int m, Int n, double *A, Int lda, double *buff);
      |                                                   ~~~~~~~~^~~~
/path/to/build-gcc/extern/scalapack/BLACS/SRC/dgsum2d_.c:167:56: error: passing argument 5 of 'BI_dvmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  167 |             BI_dvmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
      |                                                     ~~~^~~~~~
      |                                                        |
      |                                                        char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:135:59: note: expected 'double *' but argument is of type 'char *'
  135 | void BI_dvmcopy(Int m, Int n, double *A, Int lda, double *buff);
      |                                                   ~~~~~~~~^~~~
/path/to/build-gcc/extern/scalapack/BLACS/SRC/dgsum2d_.c:173:53: error: passing argument 5 of 'BI_dvmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  173 |          BI_dvmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
      |                                                  ~~~^~~~~~
      |                                                     |
      |                                                     char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:135:59: note: expected 'double *' but argument is of type 'char *'
  135 | void BI_dvmcopy(Int m, Int n, double *A, Int lda, double *buff);
      |                                                   ~~~~~~~~^~~~
/path/to/build-gcc/extern/scalapack/BLACS/SRC/dgsum2d_.c:227:52: error: passing argument 5 of 'BI_dvmcopy' from incompatible pointer type [-Wincompatible-pointer-types]
  227 |          BI_dvmcopy(Mpval(m), Mpval(n), A, tlda, bp->Buff);
      |                                                  ~~^~~~~~
      |                                                    |
      |                                                    char *
/path/to/build-gcc/extern/scalapack/BLACS/SRC/Bdef.h:135:59: note: expected 'double *' but argument is of type 'char *'
  135 | void BI_dvmcopy(Int m, Int n, double *A, Int lda, double *buff);
      |                                                   ~~~~~~~~^~~~
make[6]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/dgsum2d_.c.o] Error 1
make[5]: *** [CMakeFiles/scalapack.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [extern/scalapack-cmake/src/scalapack-stamp/scalapack-build] Error 2
make[2]: *** [extern/CMakeFiles/scalapack.dir/all] Error 2
make[1]: *** [extern/CMakeFiles/scalapack.dir/rule] Error 2
```

### CODE REVIEW

File: BLACS/SRC/igamx2d_.c [hunk 1]
```diff
@@ -277,7 +277,7 @@ F_VOID_FUNC igamx2d_(Int *ConTxt, F_CHAR scope, F_CHAR top, Int *m, Int *n,
 	 	       ctxt->scp->comm);
          if (ctxt->scp->Iam == dest)
 	 {
-	    BI_ivmcopy(Mpval(m), Mpval(n), A, tlda, bp2->Buff);
+	    BI_ivmcopy(Mpval(m), Mpval(n), A, tlda, (int*)bp2->Buff);
```
Comment (langou) [inline BLACS/SRC/igamx2d_.c:280]: should not this be Int instead of int?

**Comment by hughcars** [comment]
Ping @langou, this should be ready to go (and #141).
